export const siteConfig = {
  name: 'NIKO IT ACADEMY',
  mainTitle: 'Курси IT | Онлайн курси для старту та розвитку твоєї кар’єри в IT | NIKO IT ACADEMY',
  faqTitle: 'FAQ | NIKO IT ACADEMY',
  aboutUsTitle: 'Команда NIKO IT ACADEMY',
  coursesTitle: 'Каталог курсів NIKO IT ACADEMY',
  blogTitle: 'Блог NIKO IT ACADEMY',
  feedbacksTitle: 'Відгуки випусників NIKO IT ACADEMY',
  mentoringTitle: 'IT менторство: індивідуальне навчання з ментором | NIKO IT ACADEMY',
  mainDescription: 'Ми допоможемо отримати професію IT-сфері та та відкрити для себе нові професійні можливості в ІТ. З нами Ви можете отримати практику на на прикладах реальних робочих задач.',
  faqDescription: 'Найчастіші питання щодо навчання, оплати на NIKO IT ACADEMY',
  aboutUsDescription: 'Все про нашу онлайн платформу NIKO IT ACADEMY',
  coursesDescription: 'Каталог курсів де Ви зможете знайти собі курс за потребами',
  blogDescription: 'Відповіді на питання про світ IT та сучасний IT ринок та його тенденції, Ви можете знайти в нашому блозі.',
  feedbacksDescription: 'Реальні відгуки випускників | NIKO IT ACADEMY',
  mentoringDescription: 'Індивідуальне навчання з ментором онлайн на нашій онлайн платформі',
}
